### PR TITLE
Send username and get acknowledgement.

### PR DESCRIPTION
**Pull request by JosiahWI**

### CODE REVIEW

**Comment by piecubed** [comment]
I'll review it tomorrow, please check the build server action, it failed.

**Comment by JosiahWI** [comment]
Yeah I need to debug that, I'll get back to you once I get it working.

**Review by piecubed — APPROVED** [review]
I think the scope of this PR is accomplished, and its safe to merge.

**Comment by JosiahWI** [comment]
I think we should figure out why it doesn't work on my computer. It doesn't need to be working to merge, but I at least want to know why. I'll research protobufs imports sometime today.

**Comment by piecubed** [comment]
What error do you get?

**Pull request merged**
